name: Test frontend

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3 # https://github.com/actions/setup-node
        with:
          node-version: 16 # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
          cache: "npm"
          cache-dependency-path: package-lock.json
      # NOTE: you cannot use secrets.GITHUB_TOKEN to access private GitHub Packages
      # within the same organisation but in a different repository.
      # quoted from https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#use-private-packages
      # Skip post-install scripts here, as a malicious
      # script could steal NODE_AUTH_TOKEN.
      # quoted from https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#use-private-packages
      - run: npm ci --ignore-scripts

  licensed:
    needs: [install_dependencies]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3 # https://github.com/actions/setup-node
        with:
          node-version: 16 # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
          cache: "npm"

      - run: npm install --production --ignore-scripts
      - uses: jonabc/setup-licensed@v1
        with:
          version: 3.x

      - id: licensed
        uses: jonabc/licensed-ci@v1
        with:
          github_token: ${{ secrets.TOKEN }}
          command: bundle exec /usr/local/bin/licensed
